version: '2'
services:
  loadblancer:
    image: nginx
    volumes:
      - /home/ubuntu/DevOps-Assignment/proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - SERVICE_NAME=load-balancer
      - SERVICE_IGNORE=true
    ports:
      - "80:80"
